#!/usr/bin/env python
# coding: utf-8

# # 15 References and index

# The index to keywords words in the text given is in the order 
# 
# _chapter number - section number . subsection_  
# 
# thus 9-3.2 is chapter 9 section 3 subsection 2.
# 
# The index was generated by searching the text for keywords and later editing these a little to group sections together where the keyword is used several times. Neither questions nor answers have been searched for keywords.

# In[ ]:




