#!/usr/bin/env python
# coding: utf-8

# # 15 References and index

# References to books and articles referred to in the text. THe index is in the order chapter number - section number . subsection this 9-3.2 is chapter 9 section 3 subsection 2.
# 
# The index was generated by searching the text for keywords and later editing these a little too group sections together where the keyword is used several times. 
